#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the ZPPZ Web monorepo.
# Prepares the FastAPI backend (venv + SQLite dev DB) and the React/Vite frontend.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
backend_dir="$repo_root/backend"
frontend_dir="$repo_root/frontend"

# --- System dependency: python venv/ensurepip (default image lacks it) ---
if ! python3 -c 'import venv, ensurepip' >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq python3.12-venv
fi

# --- Backend: virtualenv + dependencies ---
cd "$backend_dir"
if [ ! -x .venv/bin/python ]; then
  python3 -m venv .venv
fi
# shellcheck disable=SC1091
. .venv/bin/activate
python -m pip install -U pip --disable-pip-version-check
pip install -r requirements-dev.txt

# --- Backend: local dev .env (never committed; production values are injected
# by the deploy pipeline). Only create it when missing so local edits survive. ---
if [ ! -f "$backend_dir/.env" ]; then
  cat > "$backend_dir/.env" <<EOF
# Local Cloud Agent dev configuration (generated by .cursor/install.sh).
DATABASE_URL=sqlite:///./zppz_v2.db
DATA_DIR=$backend_dir/data
PUBLIC_BASE_URL=http://localhost:8000
SECURE_COOKIES=false
CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:4173,http://127.0.0.1:4173
SESSION_COOKIE_NAME=zppz_session
SESSION_EXPIRE_HOURS=168
MAX_UPLOAD_MB=100
ALLOWED_EXTENSIONS=zip,7z,rar
SLOW_REQUEST_MS=500
SECRET_KEY=zppz-local-dev-secret-key-change-me
WEBHOOK_SIGNING_MASTER_KEY=zppz-local-dev-webhook-key-change-me
ADMIN_SEED_CODE=admin
ADMIN_SEED_PASSWORD=zppz-local-admin
OBJECT_STORAGE_BACKEND=local
WEB_CONCURRENCY=1
DB_POOL_SIZE=5
DB_MAX_OVERFLOW=5
DB_POOL_TIMEOUT=30
DB_POOL_RECYCLE=1800
EOF
fi

# --- Backend: build/migrate the dev database and seed default data + admin.
# Idempotent: safe to run on every install. ---
python -m app.prepare

# --- Frontend: dependencies + production build (backend serves ./dist and the
# runtime-performance test depends on it). ---
cd "$frontend_dir"
npm ci
# Point the OpenAPI type generator at the backend venv interpreter.
PYTHON="$backend_dir/.venv/bin/python" npm run build

echo "ZPPZ Web environment ready."
