import { useState } from "react";
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, FormControlLabel, IconButton, Paper, Snackbar, Stack, ToggleButton, ToggleButtonGroup, Tooltip, Typography } from "@mui/material";
import { Check, Clock3, FileCheck2, RefreshCw, Trash2, Upload } from "lucide-react";
import { api, formatDuration, formatMB, formatTime, type StoredFileRead, type SubmissionTargetRead, type Track } from "../api/v1";
import { PageHeader, ResourceState, useResource } from "../components/PagePrimitives";
import Stage2SwapPanel from "../components/Stage2SwapPanel";
import { useAuth } from "../contexts/AuthContext";
import { useConfig } from "../contexts/ConfigContext";

export default function SubmissionPage() {
  return <Stack spacing={3}><SubmissionPageContent /><Stage2SwapPanel /></Stack>;
}

function SubmissionPageContent() {
  const targets = useResource(api.submissionTargets, []);
  const submissions = useResource(api.mySubmissions, []);
  const [trackChoices, setTrackChoices] = useState<Record<number, Track>>({});
  const [banAcknowledgements, setBanAcknowledgements] = useState<Record<number, boolean>>({});
  const [busyId, setBusyId] = useState<number | "exhibition" | null>(null);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const { user } = useAuth();
  const { refreshGuessAvailability } = useConfig();
  if (user?.identity !== "participant") return <Stack spacing={3}><PageHeader icon={Upload} title="投稿" /><Alert severity="info">仅参赛者账号开放谱面投稿。</Alert></Stack>;
  const exhibitions = submissions.data?.filter((item) => item.track === "exhibition") ?? [];

  function choice(target: SubmissionTargetRead): Track { return trackChoices[target.song.id] || target.submission?.track || "normal"; }
  function chooseTrack(songId: number, nextTrack: Track) { setTrackChoices((current) => nextTrack === "j" ? Object.fromEntries((targets.data?.targets || []).map((target) => [target.song.id, target.song.id === songId ? "j" : "normal"])) : { ...current, [songId]: "normal" }); }
  function storeSubmission(next: StoredFileRead, songId?: number) {
    submissions.updateData((items) => {
      const existingIndex = items.findIndex((item) => item.id === next.id);
      if (existingIndex < 0) return [next, ...items];
      return items.map((item, index) => index === existingIndex ? next : item);
    });
    if (songId !== undefined) targets.updateData((current) => ({ ...current, targets: current.targets.map((target) => target.song.id === songId ? { ...target, submission: next } : target) }));
  }
  async function changeTrack(target: SubmissionTargetRead, nextTrack: Track) { if (!target.submission || target.submission.track === nextTrack) return; setBusyId(target.song.id); setError(""); try { const updated = await api.updateSubmissionTrack(target.submission.id, nextTrack); storeSubmission(updated, target.song.id); setMessage(nextTrack === "j" ? "已切换为 J 投稿" : "已切换为普通投稿"); await refreshGuessAvailability(); setTrackChoices({}); } catch (err) { setTrackChoices({}); setError(err instanceof Error ? err.message : "类型切换失败"); } finally { setBusyId(null); } }
  async function upload(target: SubmissionTargetRead, file?: File) { if (!file) return; setBusyId(target.song.id); setError(""); try { const acknowledged = banAcknowledgements[target.song.id] ?? false; const updated = target.submission ? await api.replaceSubmission(target.submission.id, choice(target), file, acknowledged) : await api.uploadSubmission(target.song.id, choice(target), file, acknowledged); storeSubmission(updated, target.song.id); setMessage("解析与公开包重打包完成"); await refreshGuessAvailability(); setTrackChoices({}); } catch (err) { setError(err instanceof Error ? err.message : "上传校验失败，原投稿未受影响"); } finally { setBusyId(null); } }
  async function uploadExhibition(file?: File) { if (!file) return; setBusyId("exhibition"); setError(""); try { storeSubmission(await api.uploadExhibition(file)); setMessage("场外投稿已解析并生成公开包"); await refreshGuessAvailability(); } catch (err) { setError(err instanceof Error ? err.message : "场外投稿校验失败"); } finally { setBusyId(null); } }
  async function remove(file: StoredFileRead, songId?: number) { if (!window.confirm(`确认删除“${file.file_name}”？`)) return; setBusyId(songId ?? "exhibition"); try { await api.deleteSubmission(file.id); submissions.updateData((items) => items.filter((item) => item.id !== file.id)); if (songId !== undefined) targets.updateData((current) => ({ ...current, targets: current.targets.map((target) => target.song.id === songId ? { ...target, submission: null } : target) })); await refreshGuessAvailability(); } catch (err) { setError(err instanceof Error ? err.message : "删除失败"); } finally { setBusyId(null); } }

  return <Stack spacing={3}><PageHeader icon={Upload} title="投稿" meta={`${targets.data?.targets.filter((item) => item.submission).length ?? 0} 个正赛 / J 投稿，${exhibitions.length} 个场外投稿`} />{targets.data && !targets.data.is_open ? <Alert severity="warning">当前阶段未开放普通与 J 投稿。</Alert> : null}{error ? <Alert severity="error" aria-live="polite">{error}</Alert> : null}<ResourceState loading={targets.loading} error={targets.error} />{targets.data?.targets.length ? <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "repeat(2, minmax(0, 1fr))" }, gap: 2 }}>{targets.data.targets.map((target) => <SubmissionCard key={target.song.id} target={target} selectedTrack={choice(target)} banAcknowledged={banAcknowledgements[target.song.id] ?? false} onBanAcknowledged={(checked) => setBanAcknowledgements((current) => ({ ...current, [target.song.id]: checked }))} disabled={!targets.data?.is_open || busyId !== null} busy={busyId === target.song.id} onTrack={(track) => { chooseTrack(target.song.id, track); if (target.submission) void changeTrack(target, track); }} onUpload={(file) => void upload(target, file)} onRemove={() => target.submission && void remove(target.submission, target.song.id)} />)}</Box> : null}<Paper variant="outlined" sx={{ p: { xs: 2, md: 2.5 }, borderStyle: "dashed" }}><Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ justifyContent: "space-between", alignItems: { sm: "center" } }}><Box><Typography variant="h3">场外投稿</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>无需关联曲目，数量不限；上传成功后立即公开，不参与作者竞猜。</Typography></Box><Button component="label" variant="contained" startIcon={<Upload size={16} />} disabled={!targets.data?.is_open || busyId !== null}>{busyId === "exhibition" ? "上传、解析并重打包中…" : "上传场外包"}<input hidden type="file" accept=".zip,.7z,.rar" onChange={(event) => { void uploadExhibition(event.target.files?.[0]); event.currentTarget.value = ""; }} /></Button></Stack>{exhibitions.length ? <Stack spacing={1} sx={{ mt: 2 }}>{exhibitions.map((file) => <FileSummary key={file.id} file={file} actions={<Tooltip title="删除场外投稿"><IconButton aria-label={`删除 ${file.file_name}`} color="error" disabled={busyId !== null} onClick={() => void remove(file)}><Trash2 size={17} /></IconButton></Tooltip>} />)}</Stack> : null}</Paper><Snackbar open={Boolean(message)} autoHideDuration={3000} onClose={() => setMessage("")} message={message} slotProps={{ content: { "aria-live": "polite" } }} /></Stack>;
}

function SubmissionCard({ target, selectedTrack, banAcknowledged, onBanAcknowledged, disabled, busy, onTrack, onUpload, onRemove }: { target: SubmissionTargetRead; selectedTrack: Track; banAcknowledged: boolean; onBanAcknowledged: (checked: boolean) => void; disabled: boolean; busy: boolean; onTrack: (track: "normal" | "j") => void; onUpload: (file?: File) => void; onRemove: () => void }) {
  const submitted = target.submission;
  return <Card variant="outlined"><CardContent><Stack direction="row" sx={{ justifyContent: "space-between", alignItems: "flex-start", gap: 2 }}><Box sx={{ minWidth: 0 }}><Stack direction="row" spacing={1} useFlexGap sx={{ alignItems: "center", flexWrap: "wrap" }}><Typography variant="h3" sx={{ overflowWrap: "anywhere" }}>{target.song.song_name}</Typography><Chip size="small" color={target.source_kind === "self" ? "primary" : "secondary"} label={target.source_kind === "self" ? "自选" : "抽中"} /></Stack><Typography color="text.secondary" sx={{ mt: 0.5 }}>{target.song.artist}</Typography></Box>{submitted ? <Chip size="small" color="success" icon={<Check size={14} />} label="已投稿" /> : <Chip size="small" variant="outlined" label="待投稿" />}</Stack><FormControlLabel control={<Checkbox size="small" checked={banAcknowledged} onChange={(event) => onBanAcknowledged(event.target.checked)} />} label="若查重提示疑似 Ban，确认这不是同一首曲目" sx={{ mt: 1, alignItems: "flex-start" }} />{submitted ? <FileSummary file={submitted} /> : null}<Stack direction={{ xs: "column", sm: "row" }} sx={{ mt: 2, alignItems: { xs: "stretch", sm: "center" }, justifyContent: "space-between", gap: 1.5 }}><ToggleButtonGroup size="small" exclusive value={selectedTrack} aria-label="投稿赛道" sx={{ width: { xs: "100%", sm: 224 }, "& .MuiToggleButton-root": { flex: 1, minWidth: 0 } }} onChange={(_, value: "normal" | "j" | null) => { if (value) onTrack(value); }}><ToggleButton value="normal">普通赛道</ToggleButton><ToggleButton value="j">J赛道</ToggleButton></ToggleButtonGroup><Stack direction="row" spacing={1}><Button component="label" variant={submitted ? "outlined" : "contained"} startIcon={submitted ? <RefreshCw size={16} /> : <Upload size={16} />} disabled={disabled}>{busy ? "上传、解析并重打包中…" : submitted ? "替换" : "上传"}<input hidden type="file" accept=".zip,.7z,.rar" onChange={(event) => { onUpload(event.target.files?.[0]); event.currentTarget.value = ""; }} /></Button>{submitted ? <Tooltip title="删除"><IconButton aria-label={`删除 ${target.song.song_name} 投稿`} color="error" disabled={disabled} onClick={onRemove}><Trash2 size={18} /></IconButton></Tooltip> : null}</Stack></Stack></CardContent></Card>;
}

function FileSummary({ file, actions }: { file: StoredFileRead; actions?: React.ReactNode }) {
  const checks = file.validation;
  return <Paper variant="outlined" sx={{ p: 1.5, mt: 2, bgcolor: "background.default" }}><Stack direction="row" spacing={1} sx={{ alignItems: "center", justifyContent: "space-between" }}><Box sx={{ minWidth: 0 }}><Typography variant="body2" noWrap title={file.file_name} sx={{ fontWeight: 700 }}>{file.file_name}</Typography><Typography variant="caption" color="text.secondary">{formatMB(file.file_size)} · {formatTime(file.created_at)}</Typography></Box>{actions}</Stack><Stack direction="row" spacing={1} useFlexGap sx={{ mt: 1, flexWrap: "wrap", alignItems: "center" }}><Chip size="small" icon={<Clock3 size={13} />} label={formatDuration(file.track_duration_seconds)} /><Chip size="small" color={file.public_package_ready ? "success" : "default"} icon={<FileCheck2 size={13} />} label={file.public_package_ready ? "公开包就绪" : "等待公开包"} />{checks ? Object.entries({ maidata: "maidata", track: "track", background: "背景", duration: "时长" }).map(([key, label]) => <Chip key={key} size="small" variant="outlined" color={checks[key as keyof typeof checks] ? "success" : "error"} label={`${label} ${checks[key as keyof typeof checks] ? "✓" : "×"}`} />) : null}</Stack></Paper>;
}
