import { useState } from "react";
import { Alert, Button, Checkbox, Chip, IconButton, Paper, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, Tooltip, Typography } from "@mui/material";
import { Check, Download, RefreshCw, Trash2 } from "lucide-react";
import { api, formatDuration, formatMB, formatTime, type StoredFileRead, type Track } from "../../api/v1";
import { ResourceState, useResource } from "../../components/PagePrimitives";
import { BatchDeleteDialog } from "./AdminShared";

export default function AdminSubmissions() {
  const [filter, setFilter] = useState<Track | "all">("all");
  const files = useResource((signal) => api.adminSubmissions(filter, signal), [filter]);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [error, setError] = useState("");
  async function remove(file: StoredFileRead) { if (!window.confirm(`确认删除 ${file.file_name}？`)) return; try { await api.deleteAdminSubmission(file.id); setSelected((current) => { const next = new Set(current); next.delete(file.id); return next; }); files.updateData((items) => items.filter((item) => item.id !== file.id)); } catch (err) { setError(err instanceof Error ? err.message : "删除失败"); } }
  async function removeSelected() { setDeleting(true); setError(""); try { await api.batchDeleteAdminSubmissions([...selected]); files.updateData((items) => items.filter((item) => !selected.has(item.id))); setSelected(new Set()); setDeleteOpen(false); } catch (err) { setError(err instanceof Error ? err.message : "批量删除失败"); setDeleteOpen(false); } finally { setDeleting(false); } }
  return <Stack spacing={2}>
    <Stack direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ justifyContent: "space-between" }}><Tabs value={filter} onChange={(_, value) => { setFilter(value); setSelected(new Set()); }}><Tab value="all" label="全部" /><Tab value="normal" label="普通" /><Tab value="j" label="J 赛道" /><Tab value="exhibition" label="场外" /></Tabs><Stack direction="row" spacing={1} useFlexGap sx={{ flexWrap: "wrap" }}><Button variant="outlined" startIcon={<Check size={16} />} onClick={() => setSelected(new Set(files.data?.map((item) => item.id) || []))}>全选</Button><Button variant="contained" startIcon={<Download size={16} />} disabled={!selected.size} onClick={() => void api.downloadAdminSubmissions([...selected], filter).catch((err) => setError(err.message))}>下载 {selected.size} 份</Button><Button color="error" variant="outlined" startIcon={<Trash2 size={16} />} disabled={!selected.size} onClick={() => setDeleteOpen(true)}>删除 {selected.size} 份</Button></Stack></Stack>
    {error ? <Alert severity="error">{error}</Alert> : null}<ResourceState loading={files.loading} error={files.error} empty={!files.data?.length ? "暂无投稿" : undefined} />
    {files.data?.length ? <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell padding="checkbox"><Checkbox checked={selected.size === files.data.length} indeterminate={selected.size > 0 && selected.size < files.data.length} onChange={(event) => setSelected(event.target.checked ? new Set(files.data?.map((item) => item.id)) : new Set())} slotProps={{ input: { "aria-label": "选择全部投稿" } }} /></TableCell><TableCell>曲目 / 文件</TableCell><TableCell>投稿人</TableCell><TableCell>来源</TableCell><TableCell>赛道</TableCell><TableCell>时长</TableCell><TableCell>时间</TableCell><TableCell align="right">操作</TableCell></TableRow></TableHead><TableBody>{files.data.map((file) => <TableRow key={file.id} selected={selected.has(file.id)} sx={{ contentVisibility: "auto", containIntrinsicSize: "56px" }}><TableCell padding="checkbox"><Checkbox checked={selected.has(file.id)} onChange={() => setSelected((current) => { const next = new Set(current); if (next.has(file.id)) next.delete(file.id); else next.add(file.id); return next; })} slotProps={{ input: { "aria-label": `选择 ${file.file_name}` } }} /></TableCell><TableCell><Typography sx={{ fontWeight: 650 }}>{file.source_song?.song_name || "未关联曲目"}</Typography><Typography variant="caption" color="text.secondary" sx={{ overflowWrap: "anywhere" }}>{file.file_name} · {formatMB(file.file_size)}</Typography></TableCell><TableCell>{file.user?.display_name || file.user?.user_code || "-"}</TableCell><TableCell>{file.track === "exhibition" ? "场外" : file.source_kind === "self" ? "自选" : "抽中"}</TableCell><TableCell><Chip size="small" color={file.track === "j" ? "secondary" : file.track === "exhibition" ? "info" : "default"} label={file.track === "j" ? "J" : file.track === "exhibition" ? "场外" : "普通"} /></TableCell><TableCell>{formatDuration(file.track_duration_seconds)}</TableCell><TableCell>{formatTime(file.created_at)}</TableCell><TableCell align="right"><Tooltip title="下载"><IconButton size="small" aria-label={`下载投稿 ${file.file_name}`} onClick={() => void api.downloadAdminSubmission(file.id).catch((err) => setError(err.message))}><Download size={16} /></IconButton></Tooltip><Tooltip title="替换"><IconButton component="label" size="small" aria-label={`替换投稿 ${file.file_name}`}><RefreshCw size={16} /><input hidden type="file" accept=".zip,.7z,.rar" onChange={(event) => { const next = event.target.files?.[0]; if (next) void api.replaceAdminSubmission(file.id, next).then((updated) => files.updateData((items) => items.map((item) => item.id === updated.id ? updated : item))).catch((err) => setError(err.message)); event.currentTarget.value = ""; }} /></IconButton></Tooltip><Tooltip title="删除"><IconButton size="small" color="error" aria-label={`删除投稿 ${file.file_name}`} onClick={() => void remove(file)}><Trash2 size={16} /></IconButton></Tooltip></TableCell></TableRow>)}</TableBody></Table></TableContainer> : null}
    <BatchDeleteDialog open={deleteOpen} count={selected.size} label="份投稿" busy={deleting} onClose={() => setDeleteOpen(false)} onConfirm={() => void removeSelected()} />
  </Stack>;
}
